### ISSUE TITLE
Review instructions on Review assignment

### ISSUE THREAD

**Issue by lenfra** [OpenSecEd/research#1]
There are a lot of uncertainties still regarding the purpose of the review assignment. Most students still ask what the purpose of the assignment is, and what they are supposed to do, even after they have read the instructions.

**Comment by dbosk** [comment]
My intention is to drop the review assignment entirely and simply have 
it as part of the project instead.

One alternative idea I have: After each lecture (learning session) some 
students should read some research papers and present it for the class 
before the next lecture (learning session). This way the load is spread 
over the course and all students get to read some research papers. This 
also ensures that a wider variety of research papers are presented, 
which provides depth in addition to width.

**Comment by dbosk** [comment]
We've dropped this assignment now.
